# copyright 2021 Lucid Green, Inc.

required: 
  - id
  - name
  - organizationId
  - productType
  - variety
properties:
  id:
    $ref: Id.yaml
  organizationId:
    $ref: Id.yaml
  updatedOn:
    type: string
    format: date-time
    description: The date and time when the details of this product were last updated.
  name:
    type: string
    example: Kush OG
  sku:
    type: string
  upc:
    type: string
  barcode:
    type: string
  productLine:
    type: string
  productType:
    type: string
    enum:
     - "balm"
     - "bathSalts"
     - "blunt"
     - "bodyOil"
     - "breathStrips"
     - "brownie"
     - "capsule"
     - "cbdCigarettes"
     - "chocolate"
     - "cookie"
     - "cookingOil"
     - "cracker"
     - "decarbOil"
     - "disposableVape"
     - "dissolvable"
     - "eLiquid"
     - "flower"
     - "granola"
     - "gummy"
     - "hardCandy"
     - "hash"
     - "honey"
     - "infusedBeverage"
     - "inhaler"
     - "joint"
     - "kief"
     - "lube"
     - "preGround"
     - "preRolls"
     - "rollerBallGelPen"
     - "rso_oil"
     - "salve"
     - "shatter"
     - "spread"
     - "sublingual"
     - "sublingualSpray"
     - "sublingualTablet"
     - "suppository"
     - "tablet"
     - "tea"
     - "tincture"
     - "topicalCream"
     - "transdermalPatch"
     - "vape"
     - "wax"
  usage:
    type: string
    enum:
     - "medical"
     - "recreational"
  variety:
    type: string
    enum:
     - "cbd"
     - "cbn"
     - "hybrid"
     - "indica"
     - "indicaDominant"
     - "sativa"
     - "sativaDominant"
  strain:
    type: string
  totalCannabinoids:
    $ref: Amount.yaml
    description: The expected amount of total cannabinoids within the package. Note this is the marketed amount, not the tested amount.
  totalThc:
    $ref: Amount.yaml
    description: The expected amount of total thc within the package. Note this is the marketed amount, not the tested amount.
  totalCbd:
    $ref: Amount.yaml
    description: The expected amount of total cbd within the package. Note this is the marketed amount, not the tested amount.
  thcCbdRatio:
    type: string
    description: "The ratio of THC:CBD"
    example: "5:1"
  servings:
    type: number
    format: float
  servingSize:
    $ref: Amount.yaml
  packageSize:
    $ref: Amount.yaml
  description:
    type: string
    format: html
  testsDescription:
    type: string
    format: html
  testingMethodology:
    type: string
    format: html
  usageRecommendation:
    type: string
    format: html
  aboutIngredients:
    type: string
    format: html
  ingredients:
    type: array
    items:
      type: string
  specialDiet:
    type: string
    enum:
     - "glutenFree"
     - "organic"
     - "sugarFree"
     - "vegan"
  images:
    type: object
    properties:
      thumbnail:
        $ref: Image.yaml
      primary:
        $ref: Image.yaml
